name: DeployToDockerHub
on:
   push:
     branches:    
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      uses: Whitetech7417/ksu_prkom@master
      with:
        name: dockerfromgithub
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
